CREATE TABLE CONTATOS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME VARCHAR(255),
NASCIMENTO VARCHAR(12),
TELEFONE VARCHAR(30),
EMAIL VARCHAR(255),
HORARIO VARCHAR(100),
CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID)
);
